const { getStore, connectLambda } = require("@netlify/blobs");
const ORDER_STORE="lilstore-orders", INVENTORY_STORE="lilstore-inventory", INVENTORY_KEY="inventory", COUNTER_KEY="counter";
function json(statusCode,body){return{statusCode,headers:{"Content-Type":"application/json","Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"Content-Type, x-admin-pin","Access-Control-Allow-Methods":"GET, POST, OPTIONS"},body:JSON.stringify(body)}}
function orderKey(id){return `order-${String(id).replace("#","").padStart(5,"0")}`}
function normalizeOrderId(id){return String(id||"").replace("#","").trim().padStart(5,"0")}
function normalizeStatus(s){if(s==="completed")return"confirmed";return["pending","confirmed","delivered","cancelled","reintegrated"].includes(s)?s:"pending"}
function addEvent(order,type,message){order.events=Array.isArray(order.events)?order.events:[];order.events.push({type,message,at:new Date().toISOString()})}
async function nextOrderId(store){const c=await store.get(COUNTER_KEY,{type:"json"});const n=Number(c?.last||0)+1;await store.setJSON(COUNTER_KEY,{last:n,updatedAt:new Date().toISOString()});return String(n).padStart(5,"0")}
function normalizeVariant(variant){return String(variant||"").toLowerCase()==="foil"?"foil":"normal"}
function stockFieldForVariant(variant){return normalizeVariant(variant)==="foil"?"foilStock":"stock"}
function stockMovementsFromItems(items){const grouped=new Map();for(const item of(Array.isArray(items)?items:[])){const cardKey=String(item.cardKey||item.code||"").trim(),variant=normalizeVariant(item.variant),qty=Math.max(0,Math.round(Number(item.qty||0)));if(!cardKey||!qty)continue;const key=`${cardKey}:${variant}`,current=grouped.get(key)||{cardKey,variant,qty:0};current.qty+=qty;grouped.set(key,current)}return Array.from(grouped.values())}
function validateItems(items){if(!Array.isArray(items)||!items.length)return[];return items.map(i=>({cardKey:String(i.cardKey||i.publicCode||i.dotggCode||"").trim(),name:String(i.name||"Carta").trim(),code:String(i.code||i.publicCode||i.dotggCode||i.cardKey||"").trim(),variant:normalizeVariant(i.variant),qty:Math.max(1,Math.round(Number(i.qty||1))),unitPrice:Math.max(0,Math.round(Number(i.unitPrice||0))),subtotal:Math.max(0,Math.round(Number(i.subtotal||0)))})).filter(i=>i.cardKey&&i.qty>0)}
function requireAdmin(event){const pin=process.env.ADMIN_PIN||"";const got=event.headers["x-admin-pin"]||event.headers["X-Admin-Pin"]||"";if(!pin)return{ok:false,response:json(500,{error:"Falta configurar ADMIN_PIN en Netlify."})};if(got!==pin)return{ok:false,response:json(401,{error:"PIN incorrecto."})};return{ok:true}}
async function readOrder(store,id){const order=await store.get(orderKey(normalizeOrderId(id)),{type:"json"});if(!order)return null;order.status=normalizeStatus(order.status);order.events=Array.isArray(order.events)?order.events:[];if(order.status==="confirmed"&&!order.stockDiscounted)order.stockDiscounted=true;if(order.status==="reintegrated"){order.stockDiscounted=false;order.stockReintegrated=true}return order}
async function listOrders(store,status=""){const l=await store.list({prefix:"order-"});const out=[];for(const b of (l?.blobs||[])){const o=await readOrder(store,b.key.replace("order-",""));if(o&&(!status||o.status===status))out.push(o)}return out.sort((a,b)=>new Date(b.createdAt||0)-new Date(a.createdAt||0))}
async function confirmOrder(os,is,id){id=normalizeOrderId(id);const key=orderKey(id),o=await readOrder(os,id);if(!o)return{statusCode:404,body:{error:`No existe el pedido #${id}.`}};if(o.stockDiscounted||["confirmed","delivered"].includes(o.status))return{statusCode:409,body:{error:`El pedido #${id} ya descontó stock anteriormente.`,order:o}};if(["cancelled","reintegrated"].includes(o.status))return{statusCode:409,body:{error:`El pedido #${id} no puede volver a confirmarse.`,order:o}};const movements=stockMovementsFromItems(o.items);if(!movements.length)return{statusCode:422,body:{error:"El pedido no contiene movimientos de stock válidos.",order:o}};const inv=await is.get(INVENTORY_KEY,{type:"json"})||{},problems=[];for(const movement of movements){const field=stockFieldForVariant(movement.variant),cur=Number((inv[movement.cardKey]||{})[field]||0);if(cur<movement.qty)problems.push({cardKey:movement.cardKey,variant:movement.variant,requested:movement.qty,available:cur})}if(problems.length)return{statusCode:409,body:{error:"No hay stock suficiente para confirmar este pedido.",problems,order:o}};for(const movement of movements){inv[movement.cardKey]=inv[movement.cardKey]||{};const field=stockFieldForVariant(movement.variant);inv[movement.cardKey][field]=Math.max(0,Number(inv[movement.cardKey][field]||0)-movement.qty)}const now=new Date().toISOString();Object.assign(o,{status:"confirmed",confirmedAt:now,completedAt:now,stockDiscounted:true,stockReintegrated:false,stockMovements:movements});addEvent(o,"confirmed","Pedido confirmado y stock descontado.");await is.setJSON(INVENTORY_KEY,inv);await os.setJSON(key,o);return{statusCode:200,body:{ok:true,message:`Pedido #${id} confirmado y stock descontado correctamente.`,order:o,inventory:inv}}}
async function reintegrateOrder(os,is,id){id=normalizeOrderId(id);const key=orderKey(id),o=await readOrder(os,id);if(!o)return{statusCode:404,body:{error:`No existe el pedido #${id}.`}};if(o.status==="reintegrated"||o.stockReintegrated)return{statusCode:409,body:{error:"Este pedido ya fue reintegrado.",order:o}};if(!o.stockDiscounted||!["confirmed","delivered"].includes(o.status))return{statusCode:409,body:{error:"Solo se puede reintegrar un pedido que ya haya descontado stock.",order:o}};const movements=stockMovementsFromItems(Array.isArray(o.stockMovements)&&o.stockMovements.length?o.stockMovements:o.items);if(!movements.length)return{statusCode:422,body:{error:"El pedido no contiene movimientos de stock válidos.",order:o}};const inv=await is.get(INVENTORY_KEY,{type:"json"})||{};for(const movement of movements){inv[movement.cardKey]=inv[movement.cardKey]||{};const field=stockFieldForVariant(movement.variant);inv[movement.cardKey][field]=Number(inv[movement.cardKey][field]||0)+movement.qty}Object.assign(o,{status:"reintegrated",reintegratedAt:new Date().toISOString(),stockDiscounted:false,stockReintegrated:true,stockMovements:movements});addEvent(o,"reintegrated","Stock reintegrado al inventario.");await is.setJSON(INVENTORY_KEY,inv);await os.setJSON(key,o);return{statusCode:200,body:{ok:true,message:`Pedido #${id} reintegrado correctamente al stock.`,order:o,inventory:inv}}}
async function updateStatus(os,id,next){id=normalizeOrderId(id);const key=orderKey(id),o=await readOrder(os,id);if(!o)return{statusCode:404,body:{error:`No existe el pedido #${id}.`}};if(next==="cancelled"){if(o.stockDiscounted||["confirmed","delivered"].includes(o.status))return{statusCode:409,body:{error:"Este pedido ya descontó stock. Utiliza Reintegrar stock.",order:o}};if(["cancelled","reintegrated"].includes(o.status))return{statusCode:409,body:{error:`El pedido #${id} ya está ${o.status}.`,order:o}};o.status="cancelled";o.cancelledAt=new Date().toISOString();addEvent(o,"cancelled","Pedido cancelado sin afectar stock.")}else if(next==="delivered"){if(o.status!=="confirmed"||!o.stockDiscounted)return{statusCode:409,body:{error:"Solo se puede marcar como entregado un pedido confirmado.",order:o}};o.status="delivered";o.deliveredAt=new Date().toISOString();addEvent(o,"delivered","Pedido marcado como entregado.")}else return{statusCode:400,body:{error:"Estado no válido."}};await os.setJSON(key,o);return{statusCode:200,body:{ok:true,message:`Pedido #${id} actualizado a ${o.status}.`,order:o}}}
exports.handler=async(event)=>{if(event.httpMethod==="OPTIONS")return json(200,{ok:true});try{connectLambda(event);const os=getStore(ORDER_STORE),is=getStore(INVENTORY_STORE);if(event.httpMethod==="GET"){if(event.queryStringParameters?.list==="1"){const a=requireAdmin(event);if(!a.ok)return a.response;const orders=await listOrders(os,String(event.queryStringParameters?.status||""));return json(200,{ok:true,orders,count:orders.length})}const id=normalizeOrderId(event.queryStringParameters?.id||"");if(!id||id==="00000")return json(400,{error:"Falta el número de pedido."});const o=await readOrder(os,id);return o?json(200,{ok:true,order:o}):json(404,{error:`No existe el pedido #${id}.`})}if(event.httpMethod!=="POST")return json(405,{error:"Método no permitido."});let p;try{p=JSON.parse(event.body||"{}")}catch{return json(400,{error:"JSON inválido."})}const action=p.action||"create";if(action==="create"){const items=validateItems(p.items||[]);if(!items.length)return json(400,{error:"El pedido no contiene cartas válidas."});const id=await nextOrderId(os),total=items.reduce((s,i)=>s+Number(i.subtotal||i.unitPrice*i.qty||0),0),now=new Date().toISOString();const o={id,status:"pending",source:"LilStore TCG",createdAt:now,confirmedAt:null,deliveredAt:null,cancelledAt:null,reintegratedAt:null,stockDiscounted:false,stockReintegrated:false,events:[{type:"created",message:"Pedido creado.",at:now}],items,total};await os.setJSON(orderKey(id),o);return json(200,{ok:true,order:o})}const a=requireAdmin(event);if(!a.ok)return a.response;let r;if(action==="complete"||action==="confirm")r=await confirmOrder(os,is,p.orderId);else if(action==="deliver")r=await updateStatus(os,p.orderId,"delivered");else if(action==="cancel")r=await updateStatus(os,p.orderId,"cancelled");else if(action==="reintegrate")r=await reintegrateOrder(os,is,p.orderId);else return json(400,{error:"Acción no válida."});return json(r.statusCode,r.body)}catch(e){return json(500,{error:"Error interno en orders.js",message:e.message||String(e)})}};
